### ISSUE TITLE
Example does not compile

### ISSUE THREAD

**Issue by mt-bt** [krtab/fwd_ad#1]
Hello,

I tried to repro the simple example in my project - but I get this error:

![image](https://user-images.githubusercontent.com/5712325/118948463-31dcac80-b950-11eb-83f6-f586ff789149.png)

Is there anything obvious I am missing?

Thanks

**Comment by krtab** [comment]
Hi!

Thanks for your interest in fwd_ad!

Have you solved the issue? Out of curiosity, what is the use you have in mind?
